name: Node CI
on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Prepare
        run: | 
          git mv index.html.example index.html
          npm install yarn -g
        
      - name: build
        run: |
          yarn install
          yarn lint:script
          yarn build
